// let num : number = 312;
// let str : string = "joao pedro";
// let bool : boolean = true;
// let list : string[] = ["joao", "maria", "carla", "fabio"];
// let list2 : Array<number> = [20,17,24];
// let obj = { nome: "joao", estado: "RJ", idade: 23};
var listAlunos = [{ nome: "jessica", idade: 22 }, { nome: "pedro", idade: 24 }, { nome: "tirion", idade: 45 }];
// console.log(num);
// console.log(str);
// console.log(bool);
// console.log(list);
// console.log(list2);
// console.log(obj);
// console.log(obj.estado);
// console.log(obj.idade);
console.log(listAlunos);
console.log(listAlunos[2]);
